### ISSUE TITLE
The type or namespace name 'UserBuilder' does not exist in the namespace 'FluentBuilder' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by JKamsker** [StefH/FluentBuilder#22]
Using latest VS22.
It doesn't seem to work, neither with your provided samples, nor with the example  projects.
Installation of the nuget runs through, but it seems like there is no FluentBuilder namespace available.

In the build logs there seems to exist the generated code tho... 
`1>\TestBuilder\FluentBuilderGenerator\FluentBuilderGenerator.FluentBuilderSourceGenerator\.UserBuilder.g.cs(38,65,38,80): warning CS8603: Possible null reference return.`

My code: 
``` c#
using System;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            var user = new FluentBuilder.UserBuilder()
                .WithFirstName("Test")
                .WithLastName("User")
                .Build();

            Console.WriteLine($"{user.FirstName} {user.LastName}");
        }
    }
}

[FluentBuilder.AutoGenerateBuilder]
public class User
{
    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime? Date { get; set; }
}
```

**Comment by StefH** [comment]
Did you try restarting VS2022 ?

And I noticed that `file scoped namespaces` are not support by this project.

See also example project here:
https://github.com/StefH/FluentBuilder/tree/main/src-examples/BuilderConsumerNET6

**Comment by StefH** [comment]
@JKamsker 
Can you please try version 0.4.2 ?

**Comment by StefH** [comment]
@JKamsker 
Did you have time to test version 0.4.2 ?
