### ISSUE TITLE
Add WithProperty overloads that accepts the property's builder when available

### ISSUE THREAD

**Issue by danspark** [StefH/FluentBuilder#3]
Coming from https://github.com/WireMock-Net/WireMock.Net/issues/621, I suggested that the builder API could create overloads that took other builders if the property type is also annotated with the AutoGenerateBuilder attribute. I was thinking of the following API:

```csharp
        public UserDtoBuilder WithPrimaryEmail(Action<FluentBuilder.EmailDtoBuilder> action) => WithPrimaryEmail(() =>
        {
            var builder = new FluentBuilder.EmailDtoBuilder();

            action(builder);

            return builder.Build();
        });

        public UserDtoBuilder WithPrimaryEmailBuilder(FluentBuilder.EmailDtoBuilder builder) => WithPrimaryEmail(() =>
        {
            return builder.Build();
        });
```

I was looking into the code and was able to implement it with no problem. If you're interested, I could open a pull request right now, [this is my fork](https://github.com/danspark/FluentBuilder)

**Comment by StefH** [comment]
@danspark 
Thank you for your idea.

I've added this code + a check to only generate this extra method in case there is a builder defined.

https://github.com/StefH/FluentBuilder/pull/4

In case this is correct, I'll merge and create a new version.
