### ISSUE TITLE
Builder generation fails if the target type has at least one ctor with parameters

### ISSUE THREAD

**Issue by iam-mholle** [StefH/FluentBuilder#30]
Due to the following check, an exception is thrown if the target DTO has at least one ctor with parameters, even if a parameterless one is available.

https://github.com/StefH/FluentBuilder/blob/main/src/FluentBuilderGenerator/FileGenerators/FluentBuilderClassesGenerator.cs#L247-L252 

The condition should be changed to
```csharp
classSymbol.NamedTypeSymbol.Constructors.IsEmpty || classSymbol.NamedTypeSymbol.Constructors.All(c => !c.Parameters.IsEmpty)
```

Writing out the thrown exception into the `Error.g.cs` file is great to allow errors to be analyzed - wouldn't it be good to also emit a compiler warning/error via `GeneratorExecutionContext.ReportDiagnostic(...)` for such an error? I think this would make the development experience even better.

Anyway, thank you for your work on this project!

**Comment by StefH** [comment]
@iam-mholle 
Can you create a PR and also add this specific test case as an example class like here:
![image](https://user-images.githubusercontent.com/249938/169573407-d4edfa67-9552-4ed9-8c34-18ea92c0889c.png)
