### ISSUE TITLE
Builder code should handle init setter so that it doesn't generate non-compilable code

### ISSUE THREAD

**Issue by powerdude** [StefH/FluentBuilder#35]
Given the following classes:

```csharp

public class Simple
{
   public string Name { get; private set;}  // or  public string Name { get; init;}
}

[AutoGenerateBuilder(typeof(Simple))]
public partial class SimpleBuilder
{
}
```

should not generate this code in the `Build` method:

```csharp
public override Simple Build(bool useObjectInitializer = true)
        {
            if (Object?.IsValueCreated != true)
            {
                Object = new Lazy<Simple>(() =>
                {
                    if (useObjectInitializer)
                    {
                        return new Simple
                        {
                            Name = _name.Value  // this could be here if property has init but shouldn't be otherwise
                        };
                    }

                    var instance = new Simple();
                    if (_nameIsSet) { instance.Name = _name.Value; }  // this shouldn't be here since it won't compile
                    return instance;
                });
            }

            PostBuild(Object.Value);

            return Object.Value;
        }
```

Instead, for situations like this, generate the following:

```csharp
// add this method to the builder.  A user can choose to implement and add custom behavior
partial void SetName(Simple instance, string value);  //NOTE: private could be added to the front of this to force the user to implement

public override Simple2 Build(bool useObjectInitializer = true)
        {
            if (Object?.IsValueCreated != true)
            {
                Object = new Lazy<Simple2>(() =>
                {
                    if (useObjectInitializer)
                    {
                        var result = new Simple2
                        {
                            // other settable props here
                        };
                       if (_nameIsSet) { SetName( result, _name.Value); } // or try to find a method on the class that starts with Set<PropName>
                      return result;
                    }

                    var instance = new Simple2();
                    if (_nameIsSet) { SetName( instance, _name.Value); } // or try to find a method on the class that starts with Set<PropName>
                    return instance;
                });
            }

            PostBuild(Object.Value);

            return Object.Value;
        }
```

Also, this technique could be used to overcome the default constructor requirement.  

```csharp
// add this method to the builder.  A user can choose to implement and add custom behavior
partial void SetName(Simple instance, string value);

 // Developer could provide implementation like "instance = new Simple(_name);"
// only added if no default constructor found or if you don't want to find an appropriate constructor to use
private partial void CreateInstance( out Simple instance); 

public override Simple2 Build()
        {
            if (Object?.IsValueCreated != true)
            {
                Object = new Lazy<Simple2>(() =>
                {
                    Simple instance;  
                    CreateInstance(out instance);
                    if (_nameIsSet) { SetName( instance, _name.Value); }
                    return instance;
                });
            }

            PostBuild(Object.Value);

            return Object.Value;
        }
```

**Comment by StefH** [comment]
For `init` properties, I could just throw an exception that this is not supported in case `useObjectInitializer` is set to `false`. Would that be ok?

**Comment by powerdude** [comment]
I would wonder if it's necessary to even have the `useObjectInitializer`.  The whole premise of the builder is to set the properties.  A premise of the source generator builder is to remove the boiler plate code and maybe be a little smarter.  You always have to initialize the object.  The builder can be smarter and use the `init` property always to initialize the property with something like this:  `Name = _nameIsSet ? _name.Value ? (new Simple().Name);  // looks "hacky", but this way you preserve whatever default is in the class` .  If fact, this technique could be used for all settable properties and there would be no need for the `useObjectInitializer`.  After the object is built, then you could consider the suggestion about using `partial void SetName(...)` for those properties that were `private` and couldn't be set during construction.

I don't think exceptions would be the way to go with this since the situation is completely manageable by the generator and `init` properties are valid and can/should be able to set by a builder.

**Comment by StefH** [comment]
Thanks for your explanation.

- For a fix for init-only, see this PR https://github.com/StefH/FluentBuilder/pull/38

- The useObjectInitializer is still needed for now.
  I agree in the future I can use your idea like `private partial void CreateInstance( out Simple instance);`. This will be a new PR.

- Private properties, I need to think on that.

**Comment by powerdude** [comment]
Thank you for the updates.  I added a comment to #38.  

I do have a question about what `useObjectInitializer` and the `bool` fields are trying to solve.

**Comment by powerdude** [comment]
Here's a sample of a `Build` method I'd suggest:

```csharp
public override Model Build()
{
   var instance = new Model
            {
               PublicOrInitProp = _publicOrInitProp == null ? Default.PublicOrInitProp : _publicOrInitProp .Value,
           }
         if(_privateSetter != null) SetPrivateSetter(instance, _privateSetter==null ? Default.PrivateSetter : _privateSetter.Value );
      PostBuild(instance);
  return instance;
}
```

this should cover most scenarios of building a new object and provide a fair amount of flexibility.  Is this something you could consider?  If you added `CreateInstance`, then that should complete the whole picture.

**Comment by StefH** [comment]
1] What do you mean by added a comment to #38 ? I don't see this?

2]

> For the bool fields you have, could you remove them and make the lazy fields nullable? Your Without... methods can set the field to null and the code can just check for a null lazy field before using it.

Can you please provide a full example / scenario here?

3]
Can you make a new issue which describes your ideas for private?

4]
Can you also make a new issue with details on that CreateInstance idea?

**Comment by StefH** [comment]
About point 2. I also thought on this, but in a different direction.

The bool field `IsSet` could also be implemented like `IsDirty` or something. This means that in case the user sets any value (true or false), the value should be set.
But this is also something for the future; can you also make a new issue for that.

**Comment by powerdude** [comment]
I don't think you need and `IsDirty`.  A developer should be able to make any combination of calls to `With...` and `Build` and always get a new object with the latest values.  No need for the builder to know or care if there are new values or not.  Just use what's there.

**Comment by powerdude** [comment]
After some more thought, the `Without...` methods could just set defaults like it does now and you could forget about the nullable lazy fields and just always use them.  I think it boils down to what value is being added by only using the lazy when `With...` is called.

**Comment by StefH** [comment]
@powerdude 
1] What do you mean by added a comment to https://github.com/StefH/FluentBuilder/pull/38 ? I don't see this?

**Comment by StefH** [comment]
@powerdude I cannot see your comments. Did you submit your review comments?
