### ISSUE TITLE
[enhancement]: for array `with` methods, consider adding the `params` keyword for easier use

### ISSUE THREAD

**Issue by powerdude** [StefH/FluentBuilder#39]
if a property is an array, a `With` method is generated like so:

```csharp
public Model WithData(string[] value) => WithData(() => value);
```

It would nice syntactic sugar to have:

```csharp
public Model WithData(params string[] value) => WithData(() => value);
```

just so code could be `builder.WithData("bob")` instead of `builder.WithData(new[]{"bob"})`

**Comment by StefH** [comment]
https://github.com/StefH/FluentBuilder/pull/42
