### ISSUE TITLE
Bug with a class with CultureInfo

### ISSUE THREAD

**Issue by emorell96** [StefH/FluentBuilder#43]
Hi,

Thanks a lot for all the work done on this library it has been a real help!

I found a bug while working with a class that holds a CultureInfo member.

This is my class:

```csharp
public class MenuItemDisplayModel
    {
       // other members removed since the error is based on the one below
        public CultureInfo Locale { get; set; } = CultureInfo.CurrentCulture;
    }
```

The builder created this line of code:

```csharp
private Lazy<System.Globalization.CultureInfo> _locale = new Lazy<System.Globalization.CultureInfo>(() => new System.Globalization.CultureInfo(default(int)));
```

which fails because default(int) is 0 and there's no culture with that number, so I get the exception `System.Globalization.CultureNotFoundException: Culture is not supported. (Parameter 'culture')
0 (0x0000) is an invalid culture identifier.`

Is there any attribute to tell the builder to ignore the property?

Thanks!

**Comment by StefH** [comment]
@emorell96 
I understand your issue. (BTW in my unit-test it generates the default using `string.empty` which does work, however I have a feeling this is random. So `default(int)` will indeed throw an exception.

There are 2 options to fix it:

1. I could try to find the default value defined in the class, like you did)
2. Or you should use the https://github.com/StefH/FluentBuilder#two-define-a-class-which-needs-to-act-as-a-builder option and then there should be a way to override a default method like:
   `SetLocaleDefault()`
   
   
For now I'll investigate solution 1.

**Comment by StefH** [comment]
https://github.com/StefH/FluentBuilder/pull/44

**Comment by StefH** [comment]
https://github.com/StefH/FluentBuilder/pull/45
