### ISSUE TITLE
FluentBuilder 0.10.0 requires at least Visual Studio 17.11.5

### ISSUE THREAD

**Issue by benjaminoerskov** [StefH/FluentBuilder#66]
Considering the following class:
```c#
[AutoGenerateBuilder]
public class ServiceClientOptions
{
    public bool Passthrough { get; set; } = false;
}
``` 
This works with version 0.9.2, but after update to v0.10.0, I get the error:

> Error (active)	CS0122	'AutoGenerateBuilderAttribute' is inaccessible due to its protection level.

What am I missing? Is there a migration guide for v0.10.0?

**Comment by StefH** [comment]
I need to check.

Can you provide a example project which mimics this issue?

**Comment by benjaminoerskov** [comment]
While creating an example project I noticed the following warning:
> Severity Code Description Project File Line Suppression StateWarning (active) CS9057 The analyzer assembly '[...]\FluentBuilderGenerator.dll' references version '4.11.0.0' of the compiler, which is newer than the currently running version '4.10.0.0'. WebApplication1 [...]\WebApplication1\CSC 1

After updating my Visual Studio all FluentBuilder errors were gone. 
Sorry to bother you with this!

**Comment by StefH** [comment]
Thank you for this issue.

Can you provide the version number of Visual Studio?

**Comment by StefH** [comment]
https://github.com/StefH/FluentBuilder/pull/73
